### ISSUE TITLE
mCellRecyclerView is null crash while starting demo app

### ISSUE THREAD

**Issue by vladbph** [evrencoskun/TableView#259] opened 2019-10-11 18:18 UTC
public CellLayoutManager()
        this.mCellRecyclerView = tableView.getCellRecyclerView();
gets null, because tableView did not set it yet. 

You either don't do prefetch in TableView.initialize() or do this:
        // CellRecyclerView recyclerView = new CellRecyclerView(getContext());
        mCellRecyclerView = new CellRecyclerView(getContext());

**Comment by MGaetan89** [comment] 2019-10-12 19:08
I think this is a duplicate of #245.
I have suggested a fix for this in #247.

**Comment by MGaetan89** [comment] 2019-10-12 21:01
The fix has been merged to master.
Can you close this issue if the sample app now works for you?

**Comment by MGaetan89** [comment] 2019-11-13 07:38
@vladbph did you have a chance to check if the crash is fixed for you in master?

**Comment by vladbph** [comment] 2019-11-13 17:11
yes, sorry for late reply. All good now.

**Comment by vladbph** [comment] 2019-11-13 17:11
works now

**Closed** 2019-11-13 17:11 UTC
